name: skyway_interop
version: 1.0.0
description: informal skyway interop
author: Riku Tanide <riku@tanide.net>
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0