name: skyway_interop
version: 1.0.0
description: informal skyway interop
author: Riku Tanide <riku@tanide.net>
environment:
  sdk: '>=2.0.0 <3.0.0'
dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0